# Generated by Django 4.0 on 2021-12-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='total_capacity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
